# Written by 2152-901
name: senseboard
description: A accessibility app for vision and hearing disabilities.
publish_to: 'none'
version: 1.0.0+1
 
environment:
  sdk: '>=3.0.0 <4.0.0'
 
dependencies:
  flutter:
    sdk: flutter
 
  # Vision dependencies
  camera: ^0.11.0+2
  google_mlkit_text_recognition: ^0.13.0
  flutter_tts: ^4.2.0
 
  # Hearing dependencies
  speech_to_text: ^7.0.0
  vibration: ^3.1.0

  shared_preferences: ^2.3.0
  permission_handler: ^11.3.0
 
  cupertino_icons: ^1.0.8
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
 
flutter:
  uses-material-design: true
 
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpeg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.jpeg"
